config/routes.rb
Ozer::Application.routes.draw do
  resource :account, :controller => :users
  match "login", :to => "user_sessions#new", :as => :login
  match "authenticate", :to => "user_sessions#create", :as => :authenticate
  match "logout", :to => "user_sessions#destroy", :as => :logout

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  resources :photos do
    collection do
      get :untouched
      post :edit_multiple
      put :update_multiple
      get :upload
      get :scan
    end
  end
  resources :albums do
    collection do
      get :untouched
    end
    resources :tags do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
    resources :photos do
      collection do
        get :untouched
        get :upload
        get :edit_multiple
      end
    end
  end
  resources :collections do
    resources :albums do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
  end

  resources :tags, :shallow => true do
    resources :photos
    resources :albums
  end

  resources :users, :controller => "admin/users"

  root :to => "collections#index"

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :collection_albums
  has_many :albums, :through => :collection_albums
  attr_accessor :album_list

  validates :title, :presence => true

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def album_list=(albums)
    self.albums = Album.find(albums.map { |album| album[0] })
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :check_public_access
  before_filter :require_role_admin, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @collections = Collection.where(owner: @current_user.name)
    respond_to do |format|
      format.html
      format.json { render :json => @collections }
      format.xml { render :xml => @collections }
    end
  end

  def show
    @collection = Collection.find(params[:id])
    @albums = @collection.albums.find(:all, :order => 'title')
    if @current_user == @collection.owner
      respond_to do |format|
        format.html
        format.json { render :json => @collection }
        format.xml { render :xml => @collection }
      end
    end
  end

  def new
    @collection = Collection.new

  end


  def create
    @collection = Collection.new(params[:collection])
    if @collection.save
      @collection.update_attribute("owner", current_user.name)
      flash[:notice] = "Koleksiyon oluşturuldu, albüm ekleyebilirsiniz"
      redirect_to new_collection_album_path(@collection)
    else
      render :action => :new
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(params[:collection])
      flash[:notice] = "Koleksiyon güncellendi!"
      redirect_to @collection
    else
      render :action => :edit
    end
  end

  def destroy
    @collection = Collection.find(params[:id])
    if @collection.destroy
      redirect_to collections_path
    else
      redirect_to @collection
    end
  end

end

app/views/collections/_form.html.erb
<%= form.label :title, :'Başlık', {:class => 'big'} %><br/>
<%= form.text_field :title, {:class => 'big'} %><br/>

<%= form.label :description, 'Açıklama',{:class=>'input'} %><br/>
<%= form.text_area :description, size: "40x10" , :class => 'input' %><br/>

<% unless @collection.albums.empty? %>
    <%= form.label :albums %><br/>
    <div id="collection_albums">
      <% for album in @collection.albums %>
          <%= form.fields_for :album_list do |album_fields| %>
<span>
<%= image_tag "delete-24x24.png", :class => "delete", :alt => "Delete" -%>

  <% if album.photos.empty? %>
	<%= album.title %>
<% else %>
<%= image_tag album.photos.first.file.album.url, :alt => album.title %>
<% end %>
  <%= album_fields.hidden_field album.id %>
</span>
          <% end %>
      <% end %>
    </div>

    <p class="clear">
      <%
        grouped_options = [
            ['Uygun Albümler', [['Buraya albüm ekle', '']]],
            ['Kullanımda Değil', Album.unused.map { |album| [album.title, album.id] }],
            ['Kullanımda', Album.used.map { |album| [album.title, album.id] }]
        ]
        grouped_options_for_select(grouped_options)
      %>
      <%= select_tag 'Buraya albüm ekle', grouped_options_for_select(grouped_options) %>
    </p>

<% end %>

app/views/collections/edit.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>Koleksiyonu Düzenle</h1>

<%= form_for @collection do |f| %>
    <%= f.error_messages %>
    <%= render :partial => "form", :object => f %>
    <%= f.submit "Güncelle" , :class => 'buttonStyle'%>
<% end %>

<%= content_for :action_links do %>
    <%= link_to("Bunu Sil", {:action => "destroy", :id => @collection},
                :confirm => "Silinsin Mi?",
                :method => :delete) %>
<% end %>
</body>
</html>

app/views/collections/index.html.erb
<!DOCTYPE html>
<html>
<body>
<div id="multipleimages">
  <% for collection in @collections %>
      <div class="thumb">
        <h3><%= link_to collection.title, collection %></h3>
        <%= link_to (image_tag collection.albums.find(:first).photos.first.file.collection.url), collection_path(collection) unless collection.albums.empty? || collection.albums.find(:first).photos.empty? %>
      </div>
  <% end %>
</div>

<%= content_for :action_links do %>
    <strong><%= link_to(current_user.name, 'account') %></strong>
    <%= link_to "Yeni Koleksiyon", new_collection_path %>

<% end %>
</body>
</html>

app/views/collections/new.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>Yeni Koleksiyon</h1>

<%= form_for @collection do |f| %>
    <%= f.error_messages %>
    <%= render :partial => "form", :object => f %>
    <%= f.submit "Oluştur" , :class => 'buttonStyle'%>
<% end %>

</body>
</html>

app/views/collections/show.html.erb
<!DOCTYPE html>
<html>
<body>

<h2><%= h @collection.title %></h2>
<p><i><%= h @collection.description %></i></p>
<hr class="seperator"/>
<% for album in @albums %>
    <div class="row">
      <div class="title">
        <%= render :partial => "photos/thumb", :locals => {:photo => album.photos.first} unless album.photos.empty? %>
        <p><%= link_to album.title, collection_album_path(@collection, album) %></p>
      </div>
      <div class="image">
        <%= render :partial => "photos/thumb", :collection => album.photos.find(:all, :limit => 5, :offset => 1), :as => :photo %>
      </div>
    </div>
<% end %>

<%= content_for :action_links do %>

    <%= link_to "Düzenle", edit_collection_path(@collection) %> |
    <%= link_to "Yeni Albüm", new_collection_album_path(@collection) %>

<% end %>
</body>
</html>